version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "nothub"
    reviewers:
      - "nothub"
    commit-message:
      prefix: "gomod"
      include: "scope"
